export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

export const ADD_FAVORITE = 'ADD_FAVORITE';

export const GET_FAVORITE_LOADING = 'GET_FAVORITE_LOADING';
export const GET_FAVORITE_SUCCESS = 'GET_FAVORITE_SUCCESS';
export const GET_FAVORITE_ERROR = 'GET_FAVORITE_ERROR';

export const DELETE_FAVORITE = 'DELETE_FAVORITE';